### ISSUE TITLE
The documentation for some dependency is missing

### ISSUE THREAD

**Issue by albertodvp** [kokobd/cabal-hoogle#17]
When I run the `generate` command I get this error:
```
Packages missing documentation: ...
```
and the list of missing dependencies is quite long.  The hoogle database is generated and some dependencies are included in the database but many are not. Unfortunately I couldn't think a way to reproduce it - I guess this depends heavily on the specific project. Do you have any idea of what I could be doing wrong? Is it expected to have some missing documentation?

I described some context [here](https://stackoverflow.com/questions/77850739/create-a-complete-hoogle-database-for-a-cabal-project-with-all-dependencies-incl).

Thank you!

**Comment by kokobd** [comment]
Thanks for reporting the problem. Here are a few things you can check:

1. Does `cabal haddock all` without `--haddock-hoogle` works for you? After running that command, you should get a link local link to some HTML file. Open it in browser, and try to navigate and see if you can find documentation for all your local packages and dependencies.
2. Did you compile `cabal-hoogle` with the same GHC of your project?
3. Are you running those commands inside a Nix shell? (`nix-shell` or `nix flake`). It's known that `cabal-hoogle` throws a lot of "missing dependencies" in Nix.

**Comment by albertodvp** [comment]
Hi @kokobd 

1. I can create html files only for the local packages (the ones I created a `.cabal` file for)
2. I used the flake defined in the project which has the same ghc version of my project (GHC8.10.7). To be sure I tried to use exactly the same GHC of my project but the result is the same.
3. Yes I am. Do you know why there are problems using nix? If so, do you know how that could be solve/are you planning to solve it?

Thank you for your time!

**Comment by kokobd** [comment]
> I can create html files only for the local packages (the ones I created a .cabal file for)

This implies that the dependencies are not built by the cabal command. Otherwise, changing the command line arguments should give different results.

> Do you know why there are problems using nix?

Within a nix shell, Nix provides those packages to Cabal, instead of relying on Cabal to install them. `cabal-hoogle` works by controlling the way `Cabal` builds packages, generating hoogle files along the way, and finally collect them to build a hoogle database. Without `Cabal` building the packages, there is no chance for `cabal-hoogle` to change this process.

I don't plan to fix it, because in Nix (either the haskell infrastructure provided by nixpkgs or haskell.nix), there is a simple and native way to enable hoogle for dependencies. You need to set `withHoogle = true;` in the argument to `shellFor`.

Depending on which Nix infrastructure your project is using, search for `withHoogle` in the page below and you will find how to configure that in your Nix based project.
- [nixpkgs](https://nixos.org/manual/nixpkgs/stable/#haskell-development-environments)
- [haskell.nix](https://input-output-hk.github.io/haskell.nix/tutorials/development.html)

Once `withHoogle = true` is added, you can enter the nix shell as usual, and there will be a `hoogle` command available, with documentation of all packages automatically loaded. (So `hoogle server --local --port 9000` will start a web server with docs available)

**Comment by albertodvp** [comment]
> This implies that the dependencies are not built by the cabal command. Otherwise, changing the command line arguments should give different results.

Yes were you expecting something else? In the cabal haddock help command, they explicitly mention that the tool is not running got dependencies 🤔


> Within a nix shell, Nix provides those packages to Cabal, instead of relying on Cabal to install them. `cabal-hoogle` works by controlling the way `Cabal` builds packages, generating hoogle files along the way, and finally collect them to build a hoogle database. Without `Cabal` building the packages, there is no chance for `cabal-hoogle` to change this process.

Thank you for taking the time to explaining this

> I don't plan to fix it, because in Nix (either the haskell infrastructure provided by nixpkgs or haskell.nix), there is a simple and native way to enable hoogle for dependencies. You need to set `withHoogle = true;` in the argument to `shellFor`.

Yes I tried that but unfortunately some documentation is broken in a specific dependency and that breaks everything so I cannot turn on that flag. 

Anyway, from what you say it looks cabal-hoogle is not expected to work in nix environments, I'm closing the issues

Thank you!

**Comment by kokobd** [comment]
> Yes I tried that but unfortunately some documentation is broken in a specific dependency and that breaks everything so I cannot turn on that flag.

@albertodvp In Nix, you can disable tests/haddock for specific packages in your dependencies. I don't remember how to do that exactly, but you may use [`haskell.lib.compose.dontHaddock`](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/haskell.section.md) or [`pkgs.haskell.lib.dontHaddock`](https://stackoverflow.com/questions/60781481/how-can-i-disable-testing-for-a-haskell-package-in-nix). Hope this helps!
